### ISSUE TITLE
Thread of example macro ideas

### ISSUE THREAD

**Issue by qpwo** [blainehansen/macro-ts#4]
Will update as I get more example ideas. Curious which of these are possible or impossible. And whether the syntax is good or bad.

### Typed destructured default args

```ts
// Original

function foo(!!tdda[
  [x, Color, 'red'],
  [y, string, 'foo'],
  [z, MyThing]
]) { ...}

// Becomes

function foo(
{x='red',y='foo',z}:
 {x: Color, y: string, z: MyThing}
) { … }
```

**Comment by qpwo** [comment]
## Const Freeze macro

```ts
// Original

!!freeze;{
  A = [1,2,3]
  B = {x: 4, y: 5}
}

// Becomes

const A = Object.freeze([1,2,3])
const B = Object.freeze({x: 4, y: 5})
```

**Comment by qpwo** [comment]
## Readonly Macro

In vanilla typescript, you can do

```ts
type MyType = Readonly<{x: number, y: string, z: number}>
```
but then on errors you don't see MyType; you see its definition. You can do
```ts
interface MyTypeI {x: number, y: string, z: number}
type MyType = Readonly<MyTypeI>

// or 
interface MyType {readonly x: number, readonly y: string, readonly z: number}
```

Both are kind of verbose.

This would be a fairly simple DecoratorMacro I think?

```tsx
// Original

!!@readonly
interface MyType {x: number, y: string, z: number, things: Thing[]}

// Becomes

interface MyType {readonly x: number, readonly y: string, readonly z: number, things: ReadonlyArray<Thing>}
```

**Comment by qpwo** [comment]
A small standard library of useful macros in this repo could be sweet

**Comment by qpwo** [comment]
## Named constants within object declaration

```ts
// Original

namedObj!!;{name=obj
  x: 5,
  rect::rectangle: {
    left: 0,
    top: 0,
    width: 100,
    height: 100,
}

rectangle.height = 100

// Becomes

const rectangle = {
  left: 0,
  top: 0,
  width: 100,
  height: 100,
}
const obj = {
  x: 5
  rect: rectangle
}
rectangle.height = 100
```

**Comment by blainehansen** [comment]
Thanks for the suggestions! :) In order:

For "Typed destructured default args", with the current structure of the library this one isn't possible, since macros aren't expanded when they're not an expression/statement/import. Check out `lib/transformers.ts::attemptVisitStatement`, specifically the `else if (ts.isFunctionDeclaration(statement))` block to see how function declarations are expanded.

However a new type of "general" macro could be introduced that just expands to anything (kinda like how rust macros just map `TokenStream` to `TokenStream`), but would probably be pretty annoying to get it all working, you'd have to add lots of type consistency checks to make sure the AST made any sense once you were done. I don't have the bandwidth to do that kind of work right now, but I'm happy to give pointers and accept pull requests :)

The rest of the macros all seem very doable :) I'm happy to offer guidance if you try to implement any of them in some package! I'm not sure this library is really canonical enough to warrant having a library of standards, and I've been working on other things lately. Feel free to make one of your own! Again I'm happy to offer feedback and pointers.

**Comment by qpwo** [comment]
Many thanks Blaine I think I will try my hand eventually. Meanwhile I'll keep adding to this idea list here if that's fine.

## Async to callback

```ts
// Original
!!callbackify
async function foo() {
    const result = await networkRequest()
    return result
}

// Becomes

async function foo() {
    const result: string  = await networkRequest()
    return result
}

async function fooCb(onDone: (s: string) => void) {
    const result: string = await networkRequest()
    onDone(result)
    return
}
```

Not sure how useful this one would be since you can already use .then … hmm

**Comment by qpwo** [comment]
## Destructured arg class constructor (like a struct or dataclass)

(Relates to "Typed destructured default args")

Since there's no way to have public/private/readonly destructured args in class constructors, and there's not notion of exact types:

```ts
// original

Dataclass!!;{
    name=Car
    color=string
    year=number
    owner=Person
}

// becomes

class Car {
    public color: string
    public year: number
    public owner: Person
    constructor(args: {color: string, year: number, owner: Person}) {
        this.color = args.color
        this.year = args.year
        this.owner = args.owner
    }
}
```

**Comment by qpwo** [comment]
## cond

```ts
// Original

cond!!;{
    x == y; x += 3
    x < y; x -= 3
    x > y; x *= 2
    x += 5
}

// Becomes

x == y ? x += 3 :
x < y ? x -= 3 :
x > y ? x *= 2 :
x += 5
```

**Comment by qpwo** [comment]
## Runtime non-null assertion

```ts
// Original
nnasrt!!;{w = x.y!.z}

// Becomes
const y = x?.y
if (y == null) {throw Error("y is not defined")}
const w = y.z
```

**Comment by qpwo** [comment]
## Calculate
```ts

// Original
const w = calculate!!;{
  const x = 10
  const y = 20
  10 * 20
}

// Becomes
const w = (() => {
  const x = 10
  const y = 20
  return 10 * 20
})()
```
